export const userConstant = {
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

    USER_LOGOUT: 'USER_LOGOUT',

    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

    USER_DETAILS_REQUEST: 'USER_DETAILS_REQUEST',
    USER_DETAILS_SUCCESS: 'USER_DETAILS_SUCCESS',
    USER_DETAILS_FAIL: 'USER_DETAILS_FAIL',
    USER_DETAILS_RESET: 'USER_DETAILS_RESET',

    USER_UPDATE_PROFILE_REQUEST: 'USER_UPDATE_PROFILE_REQUEST',
    USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
    USER_UPDATE_PROFILE_FAIL: 'USER_UPDATE_PROFILE_FAIL',

    GET_PRODUCT_DETAILS_REQUEST: 'GET_PRODUCT_DETAILS_REQUEST',
    GET_PRODUCT_DETAILS_SUCCESS: 'GET_PRODUCT_DETAILS_SUCCESS',
    GET_PRODUCT_DETAILS_FAILURE: 'GET_PRODUCT_DETAILS_FAILURE',

    CREATE_PROFILE_REQUEST: 'CREATE_PROFILE_REQUEST',
    CREATE_PROFILE_SUCCESS: 'CREATE_PROFILE_SUCCESS',
    CREATE_PROFILE_FAIL: 'CREATE_PROFILE_FAIL',

    GET_STATUS_REQUEST: 'GET_STATUS_REQUEST',
    GET_STATUS_SUCCESS: 'GET_STATUS_SUCCESS',
    GET_STATUS_FAILURE: 'GET_STATUS_FAILURE'
}
